name: Update Submodules

on:
  push:
    branches:
      - main  # Chạy khi có thay đổi trên nhánh main của repo tổng
    paths:
      - '**/*'  # Theo dõi tất cả các thay đổi trong repo (bao gồm cả submodules)

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo tổng
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.GH_TOKEN }}

      - name: Cập nhật submodule
        run: |
         
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          
          git pull origin main --allow-unrelated-histories
          git submodule update --remote --recursive
          
          git add .
          git commit -m "Auto update submodules" || echo "No changes to commit"
          git push
